# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: naloga2.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'naloga2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnaloga2.proto\x12\x07naloga2\"\x07\n\x05\x45mpty\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x02\"\x16\n\x05Index\x12\r\n\x05index\x18\x01 \x01(\x05\x32\xbc\x01\n\x07Naloga2\x12*\n\x07SendOne\x12\x0f.naloga2.Number\x1a\x0e.naloga2.Empty\x12)\n\x06GetOne\x12\x0e.naloga2.Index\x1a\x0f.naloga2.Number\x12-\n\x08SendMore\x12\x0f.naloga2.Number\x1a\x0e.naloga2.Empty(\x01\x12+\n\x06GetAll\x12\x0e.naloga2.Empty\x1a\x0f.naloga2.Number0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'naloga2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_NUMBER']._serialized_start=35
  _globals['_NUMBER']._serialized_end=58
  _globals['_INDEX']._serialized_start=60
  _globals['_INDEX']._serialized_end=82
  _globals['_NALOGA2']._serialized_start=85
  _globals['_NALOGA2']._serialized_end=273
# @@protoc_insertion_point(module_scope)
