# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc1_pb2 as grpc1__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpc1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Naloga1Stub(object):
    """Service with one RPC method
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Uppercase = channel.unary_unary(
                '/naloga1.Naloga1/Uppercase',
                request_serializer=grpc1__pb2.Sporocilo.SerializeToString,
                response_deserializer=grpc1__pb2.Sporocilo.FromString,
                _registered_method=True)


class Naloga1Servicer(object):
    """Service with one RPC method
    """

    def Uppercase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Naloga1Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Uppercase': grpc.unary_unary_rpc_method_handler(
                    servicer.Uppercase,
                    request_deserializer=grpc1__pb2.Sporocilo.FromString,
                    response_serializer=grpc1__pb2.Sporocilo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'naloga1.Naloga1', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('naloga1.Naloga1', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Naloga1(object):
    """Service with one RPC method
    """

    @staticmethod
    def Uppercase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/naloga1.Naloga1/Uppercase',
            grpc1__pb2.Sporocilo.SerializeToString,
            grpc1__pb2.Sporocilo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
